name: E-commerce-microservice-cd

on:
  workflow_run:
    workflows: ["E-commerce-microservice-ci"]
    types:
      - completed

jobs:
  ordering:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore Packages
      - name: Restore
        run: dotnet restore services/ordering/Ordering.API/Ordering.API.csproj

      # Build Project
      - name: Build
        run: dotnet build services/ordering/Ordering.API/Ordering.API.csproj --no-restore

        # Publish
      - name: Publish
        run: dotnet publish services/ordering/Ordering.API/Ordering.API.csproj -c Release -o publish

      # Create offline folder
      - name: Create offline folder
        run: |
          mkdir offline
          echo "Site is updating..." > offline/app_offline.htm

      # Upload offline file first
      - name: Upload app_offline.htm
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./offline/
          server-dir: /ecommerce/

      # Wait IIS stop
      - name: Wait for IIS shutdown
        run: sleep 10

      # Deploy app
      - name: Deploy App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./publish/
          server-dir: /ecommerce/
          exclude: |
            **/app_offline.htm
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                server: ${{ secrets.FTP_SERVER }}
                username: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                protocol: ftp
                local-dir: ./publish/
                server-dir: /ecommerce/
                dangerous-clean-slate: false