name: E-commerce-microservice

on:
  push:
    branches:
      - master

jobs:

  catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/catalog/catalog.csproj
      - run: dotnet build services/catalog/catalog.csproj

  basket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/basket/basket.csproj
      - run: dotnet build services/basket/basket.csproj

  discount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/discount/discount.csproj
      - run: dotnet build services/discount/discount.csproj