name: E-commerce-microservice

on:
  push:
    branches:
      - master

jobs:

  catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/Catalog.API/Catalog.API.csproj
      - run: dotnet build services/Catalog.API/Catalog.API.csproj

  basket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/Basket.API/basket.API.csproj
      - run: dotnet build services/Basket.API/basket.API.csproj

  discount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/Discount.API/discount.API.csproj
      - run: dotnet build services/Discount.API/discount.API.csproj