name: E-commerce-microservice-Ordering

on:
  push:
    branches:
      - master

jobs:
  ordering:
    runs-on: ubuntu-latest
    services:
      orderdb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: P@ssw0rd123
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v4

      - name: Show Running Containers
        run: docker ps

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore services/ordering/Ordering.API/Ordering.API.csproj
      - run: dotnet build services/ordering/Ordering.API/Ordering.API.csproj
      - run: dotnet publish services/ordering/Ordering.API/Ordering.API.csproj -c Release -o publish

      - name: Create app_offline.htm
        run: echo "Site is updating..." > publish/app_offline.htm

      - name: Upload app_offline.htm
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./publish/
          server-dir: /ecommerce/

      - name: Delete offline file locally
        run: find publish -name "app_offline.htm" -delete

      - name: Deploy App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./publish/
          server-dir: /ecommerce/

   
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          REPOSITORY: ordering-api
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY \
          -f services/ordering/Ordering.API/Dockerfile .

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY


      
                   